### ISSUE TITLE
I am not sure if this site belong here..

### ISSUE THREAD

**Issue by h3ndry** [janosh/awesome-svelte-kit#40]
link: https://files.community/
repo: https://github.com/files-community/website/

It will be better to have guidelines that make a site belong here.

**Comment by janosh** [comment]
> It will be better to have guidelines that make a site belong here.

Not sure I could come up with a generally applicable set of rules for when a site qualifies as "awesome". But feel free to make suggestions for rules. Maybe we can iterate on that to find something that works. For now, it's probably easier to decide on a case by case basis through issues like the one you opened.

https://files.community imo definitely qualifies as awesome which is why it was already added to this list in 45d3a6d.
